// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhbpxeJAjm2YdcqAggzV8IxbQ_aV4GAvA',
    appId: '1:373538584451:web:b78cbd61db65643a5068b6',
    messagingSenderId: '373538584451',
    projectId: 'fruits-hub-fe472',
    authDomain: 'fruits-hub-fe472.firebaseapp.com',
    storageBucket: 'fruits-hub-fe472.firebasestorage.app',
    measurementId: 'G-6CC9XQ0V10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCus1lpiWoZWCO3Ch4HWwdAISE8KzZ8bdc',
    appId: '1:373538584451:android:d0a4e53cb99985a65068b6',
    messagingSenderId: '373538584451',
    projectId: 'fruits-hub-fe472',
    storageBucket: 'fruits-hub-fe472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1L-dk_oHluOS38DPcG_76V2cPjfRCyFU',
    appId: '1:373538584451:ios:68bdc68351e615e55068b6',
    messagingSenderId: '373538584451',
    projectId: 'fruits-hub-fe472',
    storageBucket: 'fruits-hub-fe472.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1L-dk_oHluOS38DPcG_76V2cPjfRCyFU',
    appId: '1:373538584451:ios:68bdc68351e615e55068b6',
    messagingSenderId: '373538584451',
    projectId: 'fruits-hub-fe472',
    storageBucket: 'fruits-hub-fe472.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhbpxeJAjm2YdcqAggzV8IxbQ_aV4GAvA',
    appId: '1:373538584451:web:62e8369a34ab19755068b6',
    messagingSenderId: '373538584451',
    projectId: 'fruits-hub-fe472',
    authDomain: 'fruits-hub-fe472.firebaseapp.com',
    storageBucket: 'fruits-hub-fe472.firebasestorage.app',
    measurementId: 'G-X5R43PMXFV',
  );
}
